# -*- coding: utf-8 -*-
"""Domestic Box Office Weekends For 2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zi3crX8xlk6oMVNNKzD62vTPkMB9G-1
"""

import numpy as np
import pandas as pd
import seaborn as sns
from bs4 import BeautifulSoup
import requests
from datetime import date

url='https://www.boxofficemojo.com/weekend/by-year/2024/'

req=requests.get(url)
content=req.text
txt = req.text
soup = BeautifulSoup(txt,'html.parser')

soup=BeautifulSoup(content)

rows=soup.findAll('tr')

data = rows[8].findAll('td')

data

#Date when there is a special occasion listed
data[0].findAll('a')[0].text

data[0].findAll('span')

add_data = []
for row in rows:
    data_row = {}
    data = row.findAll('td')
    if len(data) == 0:
        continue
    if len(data[0].findAll('span')) > 0:
        #special week
        data_row['date'] = data[0].findAll('a')[0].text
    else:
        #normal week
        data_row['date'] = data[0].text
    data_row['top10_gross'] = data[1].text
    data_row['top10_lw'] = data[2].text
    data_row['overall_gross'] = data[3].text
    data_row['overall_gross_lw'] = data[4].text
    data_row['num_release'] = data[5].text
    data_row['top_release'] = data[6].text
    data_row['week'] = data[10].text
    add_data.append(data_row)
week_data = pd.DataFrame(add_data, columns = ['date', 'top10_gross', 'top10_lw', 'overall_gross', 'overall_gross_lw', 'num_release', 'top_release', 'week'])

week_data.head()

week_data.tail(10)

top10 = pd.DataFrame(week_data.groupby('top_release')['top10_gross'].\
                     sum()).\
                     sort_values('top10_gross', ascending=False)
top10.head(10)